src/Tatusiowo/DemoBundle/Entity/Activity.php
<?php

/**
 * @author Sergiusz Michalik <sergiusz.michalik@xsolve.pl>
 */

namespace Tatusiowo\DemoBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="Tatusiowo\DemoBundle\Repository\ActivityRepository")
 * @ORM\Table(name="activity")
 */
class Activity 
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     * @ORM\Column(name="title", type="string", nullable=false)
     * @Assert\NotBlank()
     */
    protected $title;

    /**
     * @var int
     * @ORM\Column(name="time_from", type="smallint", nullable=false)
     * @Assert\NotBlank()
     */
    protected $timeFrom;

    /**
     * @var int
     * @ORM\Column(name="time_to", type="smallint", nullable=false)
     * @Assert\NotBlank()
     */
    protected $timeTo;

    /**
     * @var int
     * @ORM\Column(name="age_from", type="smallint", nullable=false)
     */
    protected $ageFrom;

    /**
     * @var int
     * @ORM\Column(name="age_to", type="smallint", nullable=false)
     * @Assert\NotBlank()
     */
    protected $ageTo;

    /**
     * @var bool
     * @ORM\Column(name="outdoor", type="boolean", nullable=false)
     */
    protected $outdoor;

    /**
     * @var bool
     * @ORM\Column(name="indoor", type="boolean", nullable=false)
     */
    protected $indoor;

    /**
     * @var int
     * @ORM\Column(name="fun", type="smallint", nullable=false)
     * @Assert\NotBlank()
     */
    protected $fun;

    /**
     * @var int
     * @ORM\Column(name="creativity", type="smallint", nullable=false)
     * @Assert\NotBlank()
     */
    protected $creativity;

    /**
     * @var int
     * @ORM\Column(name="effort", type="smallint", nullable=false)
     * @Assert\NotBlank()
     */
    protected $effort;

    /**
     * @var string
     * @ORM\Column(name="description", type="text", nullable=false)
     * @Assert\NotBlank()
     */
    protected $description;

    /**
     * @var bool
     * @ORM\Column(name="approved", type="boolean", nullable=false)
     */
    protected $approved;

    /**
     * @var Image
     * @ORM\OneToOne(targetEntity="Tatusiowo\DemoBundle\Entity\Image")
     * @ORM\JoinColumn(name="image_id", referencedColumnName="id", nullable=false)
     **/
    protected $image;

    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="Tatusiowo\DemoBundle\Entity\Item", inversedBy="activities")
     * @ORM\JoinTable(name="activities_items",
     *      joinColumns={@ORM\JoinColumn(name="activity_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="item_id", referencedColumnName="id")}
     * )
     */
    protected $items;

    /**
     * @ORM\OneToMany(targetEntity="Tatusiowo\DemoBundle\Entity\ActivityDone", mappedBy="activity")
     */
    protected $activityDone;

    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="Tatusiowo\DemoBundle\Entity\User", inversedBy="activitiesToDo")
     * @ORM\JoinTable(name="activities_to_do",
     *      joinColumns={@ORM\JoinColumn(name="activity_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="item_id", referencedColumnName="id")}
     * )
     */
    protected $userToDoActivity;

    /**
     * @var \DateTime
     * @ORM\Column(name="created_at", type="datetime", nullable=false)
     */
    protected $createdAt;

    /**
     * @var \DateTime
     * @ORM\Column(name="approved_at", type="datetime", nullable=true)
     */
    protected $approvedAt;

    /**
     * @return int
     */
    public function getAgeFrom()
    {
        return $this->ageFrom;
    }

    /**
     * @return int
     */
    public function getAgeTo()
    {
        return $this->ageTo;
    }

    /**
     * @return boolean
     */
    public function isApproved()
    {
        return $this->approved;
    }

    /**
     * @return int
     */
    public function getCreativity()
    {
        return $this->creativity;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @return int
     */
    public function getEffort()
    {
        return $this->effort;
    }

    /**
     * @return int
     */
    public function getFun()
    {
        return $this->fun;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return boolean
     */
    public function isIndoor()
    {
        return $this->indoor;
    }

    /**
     * @return boolean
     */
    public function isOutdoor()
    {
        return $this->outdoor;
    }

    /**
     * @return int
     */
    public function getTimeFrom()
    {
        return $this->timeFrom;
    }

    /**
     * @return int
     */
    public function getTimeTo()
    {
        return $this->timeTo;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @return \DateTime
     */
    public function getApprovedAt()
    {
        return $this->approvedAt;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @return Image
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @return Item[]
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * @param int $ageFrom
     *
     * @return $this
     */
    public function setAgeFrom($ageFrom)
    {
        $this->ageFrom = $ageFrom;

        return $this;
    }

    /**
     * @param int $ageTo
     *
     * @return $this
     */
    public function setAgeTo($ageTo)
    {
        $this->ageTo = $ageTo;

        return $this;
    }

    /**
     * @param boolean $approved
     *
     * @return $this
     */
    public function setApproved($approved)
    {
        $this->approved = $approved;

        return $this;
    }

    /**
     * @param \DateTime $approvedAt
     *
     * @return $this
     */
    public function setApprovedAt(\DateTime $approvedAt)
    {
        $this->approvedAt = $approvedAt;

        return $this;
    }

    /**
     * @param \DateTime $createdAt
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @param int $creativity
     *
     * @return $this
     */
    public function setCreativity($creativity)
    {
        $this->creativity = $creativity;

        return $this;
    }

    /**
     * @param string $description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @param int $effort
     *
     * @return $this
     */
    public function setEffort($effort)
    {
        $this->effort = $effort;

        return $this;
    }

    /**
     * @param int $fun
     *
     * @return $this
     */
    public function setFun($fun)
    {
        $this->fun = $fun;

        return $this;
    }

    /**
     * @param boolean $indoor
     *
     * @return $this
     */
    public function setIndoor($indoor)
    {
        $this->indoor = $indoor;

        return $this;
    }

    /**
     * @param boolean $outdoor
     *
     * @return $this
     */
    public function setOutdoor($outdoor)
    {
        $this->outdoor = $outdoor;

        return $this;
    }

    /**
     * @param int $timeFrom
     *
     * @return $this
     */
    public function setTimeFrom($timeFrom)
    {
        $this->timeFrom = $timeFrom;

        return $this;
    }

    /**
     * @param int $timeTo
     *
     * @return $this
     */
    public function setTimeTo($timeTo)
    {
        $this->timeTo = $timeTo;

        return $this;
    }

    /**
     * @param string $title
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @param Image $image
     *
     * @return $this
     */
    public function setImage(Image $image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @param Item $item
     *
     * @return $this
     */
    public function addItem(Item $item)
    {
        $this->items[] = $item;

        return $this;
    }

    /**
     * @return int
     */
    public function getLike()
    {
        return rand(231, 23143);
    }

    public function getImageMockId()
    {
        // todo remove this method
        return ($this->getId() % 3) + 1;
    }
}

src/Tatusiowo/DemoBundle/Controller/ActivityController.php
<?php

namespace Tatusiowo\DemoBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Tatusiowo\DemoBundle\Entity\Activity;

class ActivityController extends BaseController
{
    /**
     * @Route("/list", name="tatusiowo_activity_list")
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @Template()
     */
    public function listAction()
    {
        return [
            'activities' => $this->getDoctrine()->getRepository('DemoBundle:Activity')->findAll()
        ];
    }

    /**
     * @param $activityId
     *
     * @Route("/{activityId}", name="tatusiowo_activity_detail")
     *
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @Template()
     */
    public function detailAction($activityId)
    {
        $activity = $this->findActivityOrFail($activityId);

        return ['activity' => $activity];
    }

    /**
     * @param $activityId
     *
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     *
     * @return Activity
     */
    private function findActivityOrFail($activityId)
    {
        $activity = $this->get('tatusiowo_activity_repository')->find($activityId);

        if (null === $activity) {
            throw new NotFoundHttpException('Activity not found.');
        }

        return $activity;
    }

}

src/Tatusiowo/DemoBundle/Controller/Admin/ActivityController.php
<?php

namespace Tatusiowo\DemoBundle\Controller\Admin;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Tatusiowo\DemoBundle\Controller\BaseController;

/**
 * Class ActivityController
 * @package Tatusiowo\DemoBundle\Controller\Admin
 */
class ActivityController extends BaseController
{
    /**
     * @Route("/approve", name="tatusiowo_admin_activity_approve")
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @Template()
     */
    public function approveAction()
    {
        return [];
    }

    /**
     * @Route("/edit", name="tatusiowo_admin_activity_edit")
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @Template()
     */
    public function editAction()
    {
        return [];
    }
}

src/Tatusiowo/DemoBundle/Resources/views/Activity/detail.html.twig
{% extends('DemoBundle::layout-with-header.html.twig') %}

{% block page_title %}{{ activity.title }}{% endblock %}

{% block content %}

<section class="single-activity grid">
    <article class="grid__item">
        <div>
            <img src="/images/photo-1.jpg" alt="{{ activity.image.title }}">
            <div class="desc">
                <div class="desc-content">
                    <h2 class="heading">{{ activity.title }}</h2>
                    <div class="grid">
                        <div class="grid__item three-quarters">
                            <ul class="icons">
                                <li class="ico ico-time">
                                    {%  if activity.timeFrom == activity.timeTo %}
                                        {{ activity.timeFrom }}
                                    {% else %}
                                        {{ activity.timeFrom }} - {{ activity.timeTo }}
                                    {% endif %}
                                    min</li>
                                <li class="ico ico-fun">{{ activity.fun }}/5</li>
                                <li class="ico ico-creative">{{ activity.creativity }}/5</li>
                                <li class="ico ico-sport">{{ activity.effort }}/5</li>
                            </ul>
                        </div><!--
                        --><div class="grid__item one-quarter">
                            <span class="ico ico-like">{{ activity.like }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </article>
</section>

<div class="activity-steps">
    <h2 class="heading">Co potrzebuję?</h2>
    <ul class="needed-eq">
    	<li>
    		<img src="/images/icons/klocki.jpg" alt="">
    		<span>klocki</span>
    	</li>
    </ul>
    <h2 class="heading">Zasady gry</h2>
    <p>{{ activity.description|raw }}</p>
    <!-- <ol>
        <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia, qui.</li>
        <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, aliquam.</li>
        <li>Lorem ipsum dolor sit.</li>
        <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, rem, possimus corporis soluta at temporibus!</li>
    </ol> -->
    <a href="#" class="start">Zaczynam zabawę</a>
    <a href="#" class="like">Lubię to</a>
</div>
{% endblock %}

src/Tatusiowo/DemoBundle/Resources/views/Activity/list.html.twig
{% extends "DemoBundle::layout-with-header.html.twig" %}

{% block page_title %}Lista zabaw{% endblock %}

{% block content %}
<section class="activities-list wrapper">
    <div class="grid grid--full jsActiveList">
        {% for activity in activities | slice(0,6) %}<!--
        --><article class="grid__item tablet-portrait--one-half desktop--one-third wide-desktop--one-third">
            <a href="{{ path('tatusiowo_activity_detail', {'activityId': activity.id}) }}" class="list-item">
                <img src="/images/photo-{{ activity.imageMockId }}.jpg" alt="{{ activity.image.title }}">
                <div class="desc">
                    <div class="desc-content">
                        <h2 class="heading">{{ activity.title }}</h2>
                        <div class="grid">
                            <div class="grid__item three-quarters">
                                <ul class="icons">
                                    <li class="ico ico-time">
                                        {%  if activity.timeFrom == activity.timeTo %}
                                            {{ activity.timeFrom }}
                                        {% else %}
                                            {{ activity.timeFrom }} - {{ activity.timeTo }}
                                        {% endif %}
                                        min</li>
                                    <li class="ico ico-fun">{{ activity.fun }}/5</li>
                                    <li class="ico ico-creative">{{ activity.creativity }}/5</li>
                                    <li class="ico ico-sport">{{ activity.effort }}/5</li>
                                </ul>
                            </div><!--
                            --><div class="grid__item one-quarter">
                                <span class="ico ico-like">{{ activity.like }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </article><!--
        -->{% endfor %}
    </div>
</section>
{% endblock %}